piro20_Ajax_Pirostagram/config/urls.py

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('post.urls')),
    path('user/', include('user.urls'))
]

piro20_Ajax_Pirostagram/post/urls.py

from django.urls import path, include
from .views import *
from django.conf import settings
from django.conf.urls.static import static

app_name = 'post'

urlpatterns = [
    path('', main, name='main'),
    path('create/', create, name='create'),
    path('update/<int:pk>', update, name='update'),
    path('detail/<int:pk>', detail, name='detail'),
    path('delete/<int:pk>', delete, name='delete'),
    path('like/', like, name='like'),
    path('comment/', comment, name='comment'),
    path('comment_delete/', comment_delete, name='comment_delete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

piro20_Ajax_Pirostagram/user/urls.py
from django.urls import path, include
from .views import *

app_name = 'user'

urlpatterns = [
    path('create/', create, name='create'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
]

piro20_Ajax_Pirostagram/post/models.py
from django.db import models
from user.models import User

class Post(models.Model):
    post_user = models.ForeignKey(User, on_delete = models.CASCADE, null=True, blank=True, related_name='post_user')
    title = models.CharField('제목',max_length=30)
    photo = models.ImageField('이미지', blank=True, upload_to='posts/%Y%m%d')
    content = models.TextField('내용', max_length=300)
    like = models.ManyToManyField(User, related_name='likes',blank=True)
    like_count = models.PositiveIntegerField(default=0) #0또는 양수만 받는 필드
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
    
class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.content
    
    

piro20_Ajax_Pirostagram/user/models.py

from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    first_name = None
    last_name = None
    username = models.CharField(max_length=10, unique=True)

    def __str__(self):
        return self.username

piro20_Ajax_Pirostagram/post/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'photo', 'content',]

piro20_Ajax_Pirostagram/user/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import User

class UserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','password1', 'password2']

piro20_Ajax_Pirostagram/post/views.py
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
import json
from django.http import JsonResponse
from .forms import PostForm
from .models import Post, Comment

def main(request):
    search_txt = request.GET.get('search_txt')
    posts = Post.objects.all().order_by('-created_at')

    if search_txt:
        posts = posts.filter(title__icontains = search_txt)
    
    ctx = {'posts': posts} 
    return render(request, 'posts/main.html', context=ctx)

def create(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.post_user = request.user
            post.save() 
            return redirect('post:main')
    else:
        form = PostForm()
        ctx = {'form': form}
    return render(request, 'posts/create.html', ctx)

def detail(request, pk):
    post = Post.objects.get(id=pk)
    comments = post.comments.all()
    ctx = {'post': post, 'comments': comments}
    return render(request, 'posts/detail.html', ctx)

def update(request, pk):
    post = Post.objects.get(id=pk)
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
        return redirect('post:main')

    else:
        form = PostForm(instance=post)
        ctx = {'form': form, 'pk': pk}
        return render(request, 'posts/update.html', ctx)

def delete(request, pk):
    if request.method == 'POST':
        Post.objects.get(id=pk).delete()
    return redirect('post:main')

@csrf_exempt
def like(request):
    req = json.loads(request.body)
    post_id = req['id']

    post = Post.objects.get(id=post_id)
    if request.user in post.like.all():
        post.like.remove(request.user)
        post.like_count -= 1
        post.save()
    else:
        post.like.add(request.user)
        post.like_count += 1
        post.save()
    post.save()
    return JsonResponse({'id': post_id, 'post_like_count': post.like_count})

@csrf_exempt
def comment(request):
    req = json.loads(request.body)
    post_id = req['id']
    comment_content = req['comment']

    pos = Post.objects.get(id=post_id)
    comment = Comment.objects.create(
        post = pos,
        author = request.user,
        content = comment_content
    )
    
    return JsonResponse({'id': comment.id, 'user': request.user.username, 'content': comment_content})
    
@csrf_exempt
def comment_delete(request):
    req = json.loads(request.body)
    comment_id = req['comment_id']

    comment = Comment.objects.get(id=comment_id)
    comment.delete()

    return JsonResponse({'id': comment_id})






piro20_Ajax_Pirostagram/user/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import auth
from .models import User
from .forms import UserForm

def create(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('post:main')
    else:
        form = UserForm()
        ctx = {'form': form}
        return render(request, 'user/user_create.html', ctx)
    
def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            user = form.get_user()
            auth.login(request, user)
            return redirect('post:main')
        return redirect('post:main')
    else:
        form = AuthenticationForm()
        ctx = {'form': form}
        return render(request, 'user/user_login.html', ctx)
    
def logout(request):
    auth.logout(request)
    return redirect('post:main')


piro20_Ajax_Pirostagram/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/navbar_footer.css' %}?after">
    <link rel="stylesheet" href="{% static 'css/main.css' %}?after">
    <link rel="stylesheet" href="{% static 'css/user_create.css' %}?after">
    <link rel="stylesheet" href="{% static 'css/post_create.css' %}?after">
    <link rel="stylesheet" href="{% static 'css/post_detail.css' %}?after">
    <title>Document</title>
</head>
<body>
    {% include 'navbar.html'%}
    {% block content %}
    {% endblock %}
    {% include 'footer.html'%}
    <script src="{% static 'js/like.js' %}"></script>
    <script src="{% static 'js/comment.js' %}"></script>
    <script src="https://kit.fontawesome.com/11b7ea1254.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>
</html>

piro20_Ajax_Pirostagram/templates/footer.html
<footer class="navbar navbar-expand-lg nav-bg footer">
    
</footer>

piro20_Ajax_Pirostagram/templates/navbar.html
<nav class="navbar navbar-expand-lg nav-bg">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">Pirostargram</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="">{{request.user.username}}님 환영합니다.</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'user:logout' %}">로그아웃</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'post:create' %}">글쓰기</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'user:login' %}">로그인</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'user:create' %}">회원가입</a>
            </li>
            {% endif %}
        </ul>
        <form action="/" method="get" class="d-flex">
          <input class="form-control me-2" name="search_txt" type="text" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>

piro20_Ajax_Pirostagram/templates/posts/create.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="post_create_container">
    <div class="post_create_modal_container">
        <form action="{% url 'post:create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}
            <button class="btn">글쓰기</button>
        </form>
    </div>
</div>
{% endblock %}

piro20_Ajax_Pirostagram/templates/posts/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="post_detail_container">
    <div class="post_detail_modal_container">
        <div class="detail_post">
            <p class="detail_title">{{post.title}}</p>
            <p class="detail_auth">{{post.post_user.username}}</p>
            <div class="detail_img_container">
                {% if post.photo.url != null %}
                <img src="{{post.photo.url}}" alt="" class="detail_img">
                {% else %}
                <img src="{% static 'image/40265653-no-연설-거품-아이콘-기호-없음-플랫-벡터-일러스트-레이션.jpg' %}" alt="" class="detail_img">
                {% endif %}
            </div>
            <p class="detail_content">{{post.content}}</p>
            <button class="btn btn-{{post.id}}" onclick="ajax_like({{post.id}})">좋아요 <span>{{post.like_count}}</span></button>
        </div>
        <div class="btns">
            {% if request.user.username == post.post_user.username %}
            <button class="btn"><a href="{% url 'post:update' post.pk %}">수정하기</a></button>
            <form action="{% url 'post:delete' post.pk %}" method="post">
                {% csrf_token %}
                <button class="btn">삭제하기</button>
            </form>
            {% endif %}
        </div>
        <div class="detail_comment">
            <div class="detail_comment_modal">
                <div>
                    <input class="comment_input" type="text" placeholder="댓글을 입력하세요"/>
                    <button class="btn" onclick="ajax_comment({{post.id}})">전송</button>
                </div>
                <ul>
                    {% for comment in comments %}
                    <span class="com_nick comment_nick-{{comment.id}}">{{comment.author}}</span>
                    <li class="comment_li-{{comment.id}}">
                        <span class="com_content comment_content-{{comment.id}}">{{comment.content}}</span>
                        {% if request.user.username == comment.author.username %}
                        <i class="fa-solid fa-trash" onclick="ajax_delete({{comment.id}})"></i>
                        {% endif %}
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock %}

piro20_Ajax_Pirostagram/templates/posts/main.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="main_container">
    <div class="main_modal_container">
        <ul>
            {% for post in posts%}
            <li>
                {% if post.photo.url != null %}
                <img src="{{ post.photo.url }}" alt="">
                {% else %}
                <img src="{% static 'image/40265653-no-연설-거품-아이콘-기호-없음-플랫-벡터-일러스트-레이션.jpg' %}" alt="">
                {% endif %}
                <div class="post_list_item_info">
                    <span class="post_title"><a href="{% url 'post:detail' post.pk %}">{{post.title}}</a></span>
                    <span class="post_user_name">{{post.post_user.username}}</span>
                    <span class="post_create_date">{{post.created_at}}</span>
                    <span><i class="fa-solid fa-heart"></i>  {{post.like_count}}</span>
                </div>
            </li>
            {% endfor %}
        </ul>
        <button class="btn"><a href="{% url 'post:create' %}">글쓰기</a></button>
    </div>
</div>
{% endblock %}

piro20_Ajax_Pirostagram/templates/posts/update.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="post_create_container">
    <div class="post_create_modal_container">
        <form action="{% url 'post:update' pk%}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}
            <button class="btn">수정하기</button>
        </form>
    </div>
</div>
{% endblock %}

piro20_Ajax_Pirostagram/templates/user/user_create.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="user_container">
    <div class="user_modal_container">
        <form action="{% url 'user:create' %}" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button class="btn">회원가입</button>
        </form>
    </div>
</div>
{% endblock %}

piro20_Ajax_Pirostagram/templates/user/user_login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="user_container">
    <div class="user_modal_container">
        <form action="{% url 'user:login' %}" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button class="btn">로그인</button>
        </form>
    </div>
</div>
{% endblock %}