아이디어사이트 과제/config/urls.py

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('devtool/', include('devtool.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

아이디어사이트 과제/devtool/urls.py
from django.urls import path
from .views import *

app_name = 'devtool'

urlpatterns = [
    path('devList/', dev_list, name='dev_list'),
    path('devCreate/', dev_create, name='dev_create'),
    path('devUpdate/<int:pk>', dev_update, name='dev_update'),
    path('devDetail/<int:pk>', dev_detail, name='dev_detail'),
    path('devDelete/<int:pk>', dev_delete, name='dev_delete'),
]

아이디어사이트 과제/posts/urls.py
from django.urls import path, include
from .views import *

app_name = 'posts'

urlpatterns = [
    path('', idea_list, name='idea_list'),
    path('ideaSubmit/', idea_submit, name='idea_submit'),
    path('ideaDetail/<int:pk>', idea_detail, name='idea_detail'),
    path('ideaUpdate/<int:pk>', idea_update, name='idea_update'),
    path('ideaDelete/<int:pk>', idea_delete, name='idea_delete'),
]

아이디어사이트 과제/devtool/models.py
from django.db import models

class devTool(models.Model):
    name= models.CharField('이름',max_length=30)
    kind = models.CharField('종류', max_length=30)
    content = models.TextField('개발툴 설명', max_length=300)

    def __str__(self):
        return self.name

아이디어사이트 과제/posts/models.py
from django.db import models

class IdeaItem(models.Model):
    title = models.CharField('아이디어명',max_length=30)
    photo = models.ImageField('이미지', blank=True, upload_to='posts/%Y%m%d')
    content = models.TextField('아이디어 설명', max_length=300)
    like = models.IntegerField('아이디어 관심도', default=0)

    def __str__(self):
        return self.title

아이디어사이트 과제/devtool/forms.py
from django import forms
from .models import devTool

class devToolForm(forms.ModelForm):
    class Meta:
        model = devTool
        fields = ('__all__')

아이디어사이트 과제/posts/forms.py
from django import forms
from .models import IdeaItem

class IdeaForm(forms.ModelForm):
    class Meta:
        model = IdeaItem
        fields = ('__all__')

아이디어사이트 과제/devtool/views.py
from django.shortcuts import render, redirect
from .forms import devToolForm
from .models import devTool

def dev_list(request):
    posts = devTool.objects.all()
    ctx = {'posts': posts}
    return render(request, 'devtool/dev_list.html', ctx)

def dev_create(request):
    if request.method == 'POST':
        form = devToolForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('devtool:dev_list')
    else:
        form = devToolForm()
        ctx = {'form':form}
        return render(request, 'devtool/dev_create.html', ctx)
        

def dev_detail(request, pk):
    post = devTool.objects.get(id=pk)
    ctx = {'post': post}
    return render(request, 'devtool/dev_detail.html', ctx)

def dev_delete(request, pk):
    if request.method == 'POST':
        devTool.objects.get(id=pk).delete()
    return redirect('devtool:dev_list')

def dev_update(request, pk):
    post = devTool.objects.get(id=pk)
    if request.method == 'POST':
        form = devToolForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
        return redirect('devtool:dev_detail', pk=pk)
    else:
        form = devToolForm(instance=post)
        ctx = { 'form' : form, 'pk' : pk}
        return render(request, 'devtool/dev_update.html', ctx)


아이디어사이트 과제/posts/views.py
from django.shortcuts import render, redirect
from .forms import IdeaForm
from .models import IdeaItem

def idea_list(request):
    posts = IdeaItem.objects.all()
    ctx = {'posts': posts}
    return render(request, 'posts/idea_list.html', ctx)

def idea_submit(request):
    if request.method == 'POST':
        form = IdeaForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
        return redirect('posts:idea_list')
    else:
        form = IdeaForm()
        ctx = {'form' : form}
        return render(request, 'posts/idea_submit.html', context=ctx)
    
def idea_detail(request, pk):
    post = IdeaItem.objects.get(id=pk)
    ctx = {'post': post}
    return render(request, 'posts/idea_detail.html', context=ctx)

def idea_update(request, pk):
    post = IdeaItem.objects.get(id=pk)
    if request.method == 'POST':
        form = IdeaForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
        return redirect('posts:idea_list')
    else:
        form = IdeaForm(instance=post)
        ctx = { 'form' : form, 'pk' : pk}
        return render(request, 'posts/idea_update.html', ctx)
    
def idea_delete(request, pk):
    if request.method == 'POST':
        IdeaItem.objects.get(id=pk).delete()
    return redirect('posts:idea_list')

아이디어사이트 과제/templates/devtool/dev_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        *{
            margin: 0;
            padding: 0;
        }

        body{
            background-color: rgb(43, 42, 42);
            color: aliceblue;
        }
    </style>
    <title>Document</title>
</head>
<body>
    <form action="{% url 'devtool:dev_create' %}" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button>등록하기</button>
    </form>
</body>
</html>

아이디어사이트 과제/templates/devtool/dev_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/dev_detail.css' %}?after">
    <title>Document</title>
</head>
<body>
    <nav>
        <p id="logo"><a href="/">MY IDEA</a></p>
        <ul>
            <li><a href="{% url 'posts:idea_submit' %}">아이디어 등록</a></li>
            <li><a href="/">아이디어 관리</a></li>
            <li><a href="{% url 'devtool:dev_create' %}">개발툴 등록</a></li>
            <li><a href="{% url 'devtool:dev_list' %}">개발툴 관리</a></li>
        </ul>
    </nav>
    <div id="container">
        <div id="item_container">
            <div class="idea_detail">Dev Tool Detail</div>
            <div class="dev_post">
                <div class="dev_article">
                    <p class="dev_name">{{post.name}}</p>
                    <p class="dev_kind">개발툴 종류 : {{post.kind}}</p>
                    <p class="dev_content">개발툴 설명 : {{post.content}}</p>
                </div>
                <div class="use_idea">
                    >만들 수 있는 SW목록
                    <ul>
                        <li>

                        </li>
                    </ul>
                </div>
            </div>
            <div class="btns">
                <form action="{% url 'devtool:dev_delete' post.pk%}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn_red">삭제</button>
                </form>
                <button class="btn_gray"><a href="{% url 'devtool:dev_list'%}">목록</a></button>
                <button class="btn_blue"><a href="{% url 'devtool:dev_update' post.pk%}">수정</a></button>
            </div>
        </div>
    </div>
</body>
</html>

아이디어사이트 과제/templates/devtool/dev_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/dev_list.css' %}?after">
    <title>Document</title>
</head>
<body>
    <nav>
        <p id="logo"><a href="/">MY IDEA</a></p>
        <ul>
            <li><a href="{% url 'posts:idea_submit' %}">아이디어 등록</a></li>
            <li><a href="/">아이디어 관리</a></li>
            <li><a href="{% url 'devtool:dev_create' %}">개발툴 등록</a></li>
            <li><a href="{% url 'devtool:dev_list' %}">개발툴 관리</a></li>
        </ul>
    </nav>
    <div id="container">
        <div id="item_container">
            <span>Dev Tool List</span>
            <ul>
                {% for post in posts %}
                <li>
                    <div class="dev_name"><a href="{% url 'devtool:dev_detail' post.pk %}">{{post.name}}</a></div>
                    <div class="dev_type">{{post.kind}}</div>
                    <div class="dev_content">{{post.content}}</div>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</body>
</html>

아이디어사이트 과제/templates/devtool/dev_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        *{
            margin: 0;
            padding: 0;
        }

        body{
            background-color: rgb(43, 42, 42);
            color: aliceblue;
        }
    </style>
</head>
<body>
    <form action="{% url 'devtool:dev_update' pk %}" method="post" >
        {% csrf_token %}
        {{form.as_p}}
        <button>수정하기</button>
    </form>
</body>
</html>

아이디어사이트 과제/templates/posts/idea_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/detail.css' %}">
    <title>Document</title>
</head>
<body>
    <nav>
        <p id="logo"><a href="/">MY IDEA</a></p>
        <ul>
            <li><a href="{% url 'posts:idea_submit' %}">아이디어 등록</a></li>
            <li><a href="/">아이디어 관리</a></li>
            <li><a href="{% url 'devtool:dev_create' %}">개발툴 등록</a></li>
            <li><a href="{% url 'devtool:dev_list' %}">개발툴 관리</a></li>
        </ul>
    </nav>
    <div id="container">
        <div id="item_container">
            <div class="idea_detail">Idea Detail</div>
            <div class="post">
                {% if post.photo.url != null %}
                <img src="{{post.photo.url}}" class="post_img" >
                {% else %}
                <img src="{% static 'image/360_F_473254957_bxG9yf4ly7OBO5I0O5KABlN930GwaMQz.jpg' %}" class="post_img" >
                {% endif %}
                <div class="post_article">
                    <p class="post_title">{{post.title}}</p>
                    <p class="post_like">아이디어 관심도 : {{post.like}}</p>
                    <p class="dev_tool">예상 개발 툴 : java</p>
                    <p class="post_content">아이디어 실행 : {{post.content}}</p>
                </div>
            </div>
            <div class="btns">
                <form action="{% url 'posts:idea_delete' post.pk%}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn_red">삭제</button>
                </form>
                <button class="btn_gray"><a href="/">목록</a></button>
                <button class="btn_blue"><a href="{% url 'posts:idea_update' post.pk%}">수정</a></button>
            </div>
        </div>
    </div>
</body>
</html>

아이디어사이트 과제/templates/posts/idea_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title>Document</title>
</head>
<body>
    <nav>
        <p id="logo"><a href="/">MY IDEA</a></p>
        <ul>
            <li><a href="{% url 'posts:idea_submit' %}">아이디어 등록</a></li>
            <li><a href="/">아이디어 관리</a></li>
            <li><a href="{% url 'devtool:dev_create' %}">개발툴 등록</a></li>
            <li><a href="{% url 'devtool:dev_list' %}">개발툴 관리</a></li>
        </ul>
    </nav>
    <div id="container">
        <div id="item_container">
            <span>Idea List</span>
            <ul>
                {% for post in posts %}
                    <li>
                        {% if post.photo.url != null %}
                        <img src="{{post.photo.url}}" class="idea_img" >
                        {% else %}
                        <img src="{% static 'image/360_F_473254957_bxG9yf4ly7OBO5I0O5KABlN930GwaMQz.jpg' %}" class="idea_img" >
                        {% endif %}
                        <span class="idea_title"><a href="{% url 'posts:idea_detail' post.pk %}">{{post.title}}</a></span>
                        <span class="dev_tool">대충 개발툴임</span>
                        <span class="idea_like">{{post.like}}</span>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</body>
</html>

아이디어사이트 과제/templates/posts/idea_submit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        *{
            margin: 0;
            padding: 0;
        }

        body{
            background-color: rgb(43, 42, 42);
            color: aliceblue;
        }
    </style>
    <title>Document</title>
</head>
<body>
    <form action="{% url 'posts:idea_submit' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <button>등록하기</button>
    </form>
</body>
</html>

아이디어사이트 과제/templates/posts/idea_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        *{
            margin: 0;
            padding: 0;
        }

        body{
            background-color: rgb(43, 42, 42);
            color: aliceblue;
        }
    </style>
</head>
<body>
    <form action="{% url 'posts:idea_update' pk %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <button>수정하기</button>
    </form>
</body>
</html>